font:
  normal:
    family: FiraMono Nerd Font
    style: Medium

  bold:
    family: FiraMono Nerd Font
    style: Bold

  size: 12.0

selection:
  save_to_clipboard: true
window:
  padding:
    x: 0
    y: 0

  dimensions:
    columns: 80
    lines: 24

colors:
  primary:
    background: '0x141414'
    foreground: '0xdadada'

  normal:
    black:   '0x302D41'
    red:     '0xF28FAD'
    green:   '0xABE9B3'
    yellow:  '0xFAE3B0'
    blue:    '0x96CDFB'
    magenta: '0xDDB6F2'
    cyan:    '0xA1EFD3'
    white:   '0xD9E0EE'

  bright:
    black:   '0x575268'
    red:     '0xF28FAD'
    green:   '0xABE9B3'
    yellow:  '0xFAE3B0'
    blue:    '0x96CDFB'
    magenta: '0xDDB6F2'
    cyan:    '0xA1EFD3'
    white:   '0xF5E0DC'
