#!/bin/bash

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

##### Bar Appearance #####
sketchybar --bar height=32 \
	blur_radius=30 \
	position=top \
	sticky=off \
	padding_left=10 \
	padding_right=10 \
	color=0x15161616 \
	corner_radius=10 \
	shadow=off

##### Changing Defaults #####
sketchybar --default icon.font="Hack Nerd Font:Bold:14.0" \
	icon.color=0xfff2f2f2 \
	label.font="Hack Nerd Font:Bold:14.0" \
	label.color=0xfff2f2f2 \
	padding_left=5 \
	padding_right=5 \
	label.padding_left=4 \
	label.padding_right=4 \
	icon.padding_left=4 \
	icon.padding_right=4

##### Adding Mission Control Space Indicators #####
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")

for i in "${!SPACE_ICONS[@]}"; do
	sid=$(($i + 1))
	sketchybar --add space space.$sid left \
		--set space.$sid associated_space=$sid \
		icon=${SPACE_ICONS[i]} \
		background.color=0x44ffffff \
		background.corner_radius=5 \
		background.height=20 \
		background.drawing=off \
		label.drawing=off \
		script="$PLUGIN_DIR/space.sh" \
		click_script="yabai -m space --focus $sid"
done

##### Adding Left Items #####
sketchybar --add item space_separator left \
	--set space_separator icon= \
	padding_left=10 \
	padding_right=10 \
	label.drawing=off \
	\
	--add item front_app left \
	--set front_app script="$PLUGIN_DIR/front_app.sh" \
	icon.drawing=off \
	--subscribe front_app front_app_switched

##### Adding Center Items #####
sketchybar --add item center_space center \
	--set center_space width=20 \
	\
	--add item clock center \
	--set clock update_freq=1 \
	script="$PLUGIN_DIR/clock.sh" \
	icon.padding_left=10 \
	icon.padding_right=10 \
	label.padding_left=10 \
	label.padding_right=10

##### Adding Right Items #####
sketchybar --add item right_space right \
	--set right_space width=20 \
	\
	--add item wifi right \
	--set wifi script="$PLUGIN_DIR/wifi.sh" \
	--subscribe wifi wifi_change \
	\
	--add item volume right \
	--set volume script="$PLUGIN_DIR/volume.sh" \
	--subscribe volume volume_change \
	\
	--add item battery right \
	--set battery script="$PLUGIN_DIR/battery.sh" \
	update_freq=60 \
	--subscribe battery system_woke power_source_change

##### Finalizing Setup #####
sketchybar --update
