#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# bsp or float (default: bsp)
#yabai -m config layout bsp

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^console$" manage=off

## Some random global settings
#yabai -m config focus_follows_mouse          autoraise
#yabai -m config focus_follows_mouse          on
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config window_topmost off
#yabai -m config window_shadow float
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.00
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0
#yabai -m config window_border on

## WITH SIP ENABLED (Installed Limelight seperately, Don't need this)

## WTIH SIP DISABLED (Limelight build into Yabai, enable it here)
yabai -m config window_border off
yabai -m config window_border_width 0
yabai -m config active_window_border_color 0xFFcba6f7
yabai -m config normal_window_border_color 0x00FFFFFF
yabai -m config insert_feedback_color 0xffd75f5f
# yabai -m window.padding.y 15
# yabai -m window.padding.x 15

## some other settings
yabai -m config auto_balance ofF
yabai -m config split_ratio 0.50
# # set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# general space settings
#yabai -m config focused_border_skip_floating  1
#yabai -m config --space 3 layout             float

## Change how yabai looks
yabai -m config layout bsp
yabai -m config top_padding 50
yabai -m config bottom_padding 40
yabai -m config left_padding 40
yabai -m config right_padding 40
yabai -m config window_gap 25

# I have a full screen terminal on space 10, so I don't want any padding on that space
yabai -m config --space 10 top_padding 0 bottom_padding 0 left_padding 0 right_padding 0 window_gap 0

yabai -m config window_animation_duration 0.15

yabai -m signal --add event=window_destroyed action="bash /Users/jesseskelton/CustomScripts/SwitchSpaces/window-focus-on-destroy.sh"

borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=3.0 style=round &

exec sketchybar

echo "yabai configuration loaded.."

#END
